(()=>{
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
$$('.reveal').forEach(el=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});io.observe(el)});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=$(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'})}}));
const menu=$('.menu'), nav=$('.nav');menu?.addEventListener('click',()=>{if(nav.style.display==='flex'){nav.style.display='none'}else{nav.style.display='flex';nav.style.position='absolute';nav.style.top='54px';nav.style.left='0';nav.style.right='0';nav.style.padding='22px';nav.style.background='#07070add';nav.style.flexDirection='column';nav.style.alignItems='center'}});
function modal(){if($('.modal'))return;const m=document.createElement('div');m.className='modal';m.innerHTML='<div class="modalbox"><button class="close">×</button><span class="eyebrow">NATA BETA</span><h2>Sei von Anfang an <em>dabei.</em></h2><p>Sichere dir deinen Platz in der ersten Nata-Generation.</p><form><input required type="email" placeholder="deine@email.de"><button>Beta sichern →</button></form><small>Kein Spam. Jederzeit abmeldbar.</small></div>';document.body.append(m);const st=document.createElement('style');st.textContent='.modal{position:fixed;inset:0;z-index:300;background:#000c;backdrop-filter:blur(18px);display:grid;place-items:center;padding:20px}.modalbox{width:min(560px,100%);padding:45px;border-radius:35px;background:#111117;color:#fff;border:1px solid #a33dff66;box-shadow:0 70px 150px #000;position:relative}.modalbox h2{font-size:48px;line-height:.9;letter-spacing:-.06em}.modalbox h2 em{color:#d39aff;font-style:normal}.modalbox p{color:#999;line-height:1.7}.modalbox form{display:flex;gap:10px;margin:25px 0}.modalbox input{flex:1;border:1px solid #fff2;background:#07070a;color:white;border-radius:99px;padding:14px}.modalbox form button{border:0;border-radius:99px;padding:14px 20px;font-weight:800}.close{position:absolute;right:15px;top:8px;border:0;background:none;color:#aaa;font-size:30px}';document.head.appendChild(st);$('.close',m).onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};$('form',m).onsubmit=e=>{e.preventDefault();$('.modalbox',m).innerHTML='<button class="close">×</button><div style="text-align:center;padding:30px"><div style="font-size:55px;color:#d39aff">✓</div><h2>Willkommen bei Nata.</h2><p>Dein Beta-Platz ist vorgemerkt.</p></div>';$('.close',m).onclick=()=>m.remove()}};
$$('[data-beta]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();modal()}));
const score=$('[data-score]');if(score){const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;let n=0;const t=setInterval(()=>{n=Math.min(11,n+1);score.textContent=n;if(n===11)clearInterval(t)},70);io.unobserve(e.target)}),{threshold:.5});io.observe(score)}
const p=$('#progress');const up=()=>{const max=document.documentElement.scrollHeight-innerHeight;p.style.width=(max?scrollY/max*100:0)+'%'};addEventListener('scroll',up,{passive:true});addEventListener('resize',up);up();
})();
